/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ProposeRouteImport } from './routes/propose'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ChallengesIdRouteImport } from './routes/challenges.$id'
import { Route as PeopleLoginRouteImport } from './routes/people_.$login'
import { Route as SubmissionsIdRouteImport } from './routes/submissions.$id'
import { Route as ChallengesIdEditRouteImport } from './routes/challenges.$id_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposeRoute = ProposeRouteImport.update({
  id: '/propose',
  path: '/propose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdRoute = ChallengesIdRouteImport.update({
  id: '/challenges/$id',
  path: '/challenges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleLoginRoute = PeopleLoginRouteImport.update({
  id: '/people_/$login',
  path: '/people/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsIdRoute = SubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdEditRoute = ChallengesIdEditRouteImport.update({
  id: '/challenges/$id_/edit',
  path: '/challenges/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/people': typeof PeopleRoute
  '/proposals': typeof ProposalsRoute
  '/propose': typeof ProposeRoute
  '/api/$': typeof ApiSplatRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/people/$login': typeof PeopleLoginRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/challenges/$id/edit': typeof ChallengesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/people': typeof PeopleRoute
  '/proposals': typeof ProposalsRoute
  '/propose': typeof ProposeRoute
  '/api/$': typeof ApiSplatRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/people/$login': typeof PeopleLoginRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/challenges/$id/edit': typeof ChallengesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builds': typeof BuildsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/moderation': typeof ModerationRoute
  '/notifications': typeof NotificationsRoute
  '/people': typeof PeopleRoute
  '/proposals': typeof ProposalsRoute
  '/propose': typeof ProposeRoute
  '/api/$': typeof ApiSplatRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/people_/$login': typeof PeopleLoginRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/challenges/$id_/edit': typeof ChallengesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builds'
    | '/leaderboard'
    | '/moderation'
    | '/notifications'
    | '/people'
    | '/proposals'
    | '/propose'
    | '/api/$'
    | '/challenges/$id'
    | '/people/$login'
    | '/submissions/$id'
    | '/challenges/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builds'
    | '/leaderboard'
    | '/moderation'
    | '/notifications'
    | '/people'
    | '/proposals'
    | '/propose'
    | '/api/$'
    | '/challenges/$id'
    | '/people/$login'
    | '/submissions/$id'
    | '/challenges/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/builds'
    | '/leaderboard'
    | '/moderation'
    | '/notifications'
    | '/people'
    | '/proposals'
    | '/propose'
    | '/api/$'
    | '/challenges/$id'
    | '/people_/$login'
    | '/submissions/$id'
    | '/challenges/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildsRoute: typeof BuildsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ModerationRoute: typeof ModerationRoute
  NotificationsRoute: typeof NotificationsRoute
  PeopleRoute: typeof PeopleRoute
  ProposalsRoute: typeof ProposalsRoute
  ProposeRoute: typeof ProposeRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ChallengesIdRoute: typeof ChallengesIdRoute
  PeopleLoginRoute: typeof PeopleLoginRoute
  SubmissionsIdRoute: typeof SubmissionsIdRoute
  ChallengesIdEditRoute: typeof ChallengesIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propose': {
      id: '/propose'
      path: '/propose'
      fullPath: '/propose'
      preLoaderRoute: typeof ProposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id': {
      id: '/challenges/$id'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people_/$login': {
      id: '/people_/$login'
      path: '/people/$login'
      fullPath: '/people/$login'
      preLoaderRoute: typeof PeopleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$id': {
      id: '/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof SubmissionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id_/edit': {
      id: '/challenges/$id_/edit'
      path: '/challenges/$id/edit'
      fullPath: '/challenges/$id/edit'
      preLoaderRoute: typeof ChallengesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildsRoute: BuildsRoute,
  LeaderboardRoute: LeaderboardRoute,
  ModerationRoute: ModerationRoute,
  NotificationsRoute: NotificationsRoute,
  PeopleRoute: PeopleRoute,
  ProposalsRoute: ProposalsRoute,
  ProposeRoute: ProposeRoute,
  ApiSplatRoute: ApiSplatRoute,
  ChallengesIdRoute: ChallengesIdRoute,
  PeopleLoginRoute: PeopleLoginRoute,
  SubmissionsIdRoute: SubmissionsIdRoute,
  ChallengesIdEditRoute: ChallengesIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
